### ISSUE TITLE
Cannot read property 'getChannelData' of undefined

### ISSUE THREAD

**Issue by GarryChang** [jackedgson/crunker#11]
Get "Cannot read property 'getChannelData' of undefined" issue.
I downloaded its and add assets folder but not working.
https://www.dl-sounds.com/royalty-free/my-little-adventure/
https://www.dl-sounds.com/royalty-free/defense-line/
please give me a solution.
Best

**Comment by ronoyama7** [comment]
sorry it was my bug.

**Comment by jaggad** [comment]
Please report the fix for future reference

**Comment by GarryChang** [comment]
I imported plugin wrong like as this
import { Crunker } from 'crunker';
but fixed 
import Crunker from 'crunker';
