### ISSUE TITLE
Blob size

### ISSUE THREAD

**Issue by GarryChang** [jackedgson/crunker#12]
I tried output audio with concatAudio function return value.
Blob size is always 4 x concatBufferSize.
is there any method to compress mp3 file size?
Best

**Comment by jaggad** [comment]
Possibly by changing the sampleRate configuration option to something lower like 16000 (16kHz) this will produce a lower quality audio which in turn has smaller file size.

**Comment by GarryChang** [comment]
Ok thanks.
is this working on safari?

**Comment by jaggad** [comment]
Should work anywhere Web Audio API is supported, so Safari should work.
Internet Explorer will not.

There is a method `notSupported()` where you can provide a callback function for unsupported browsers.
