### ISSUE TITLE
Cannot read property 'getChannelData' of undefined

### ISSUE THREAD

**Issue by FrancescoMussi** [jackedgson/crunker#14]
Hello. Is it possible to merge two blob files?

I am trying every possible way to merge the audio of two blobs. 
Your package seems the perfect solution.

But when I am trying it, I am getting the following error:

`Cannot read property 'getChannelData' of undefined`

This is the code. Just as in the doc. I am passing the two blobs as parameters:

```
let audio = new Crunker()
audio
  .fetchAudio(this.blobArray[0], this.blobArray[1])
  .then(buffers => {
    console.log({buffers})
    audio.mergeAudio(buffers);
  })
  .then(merged => {
    // => AudioBuffer
    console.log({merged})
    audio.export(merged, "audio/mp3");
  })
  .then(output => {
    // => {blob, element, url}
    console.log({output})
    audio.download(output.blob)
    document.append(output.element)
    console.log(output.url)
  })
  .catch(error => {
    console.log({error})
  });
```

This is a print of the console.log of each step:
It seems that nothing is returned from the second promise.

![screen shot 2018-09-28 at 16 35 36](https://user-images.githubusercontent.com/5312907/46211830-2c646b00-c33d-11e8-89c6-cd93dd8c031c.png)

Do you know why I am getting that error?

**Comment by Alynva** [comment]
I know that it's too late, but the code in README are wrong, probably you got it from there. It is not returning the values inside the `then` function, so to the second `then`, the parameter was `undefined`. This should works fine:

```js
let audio = new Crunker()
audio
  .fetchAudio(this.blobArray[0], this.blobArray[1])
  .then(buffers => {
    console.log({buffers})
    return audio.mergeAudio(buffers);
  })
  .then(merged => {
    // => AudioBuffer
    console.log({merged})
    return audio.export(merged, "audio/mp3");
  })
  .then(output => {
    // => {blob, element, url}
    console.log({output})
    document.body.append(output.element)
    return audio.download(output.blob)
  })
  .catch(error => {
    console.log({error})
  });
```

I will make a PR with the corrections.
