### ISSUE TITLE
Please clarify in README.md: what is the difference between merge and concat

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jackedgson/crunker#16]

**Comment by jaggad** [comment]
Merge overlays the two songs from the start (t=0). Concat appends each song to the previous one in the array. Feel free to make a PR

**Comment by Alynva** [comment]
Some images that can be used in README:

## Merge

![merge](https://user-images.githubusercontent.com/12958674/88806278-968f0680-d186-11ea-9cb5-8ef2606ffcc7.png)

## Concat

![concat](https://user-images.githubusercontent.com/12958674/88806297-9d1d7e00-d186-11ea-8cd2-c64cb0324845.png)

**Comment by jaggad** [comment]
@Alynva Thank you, I've added this to the README now
