### ISSUE TITLE
Mp3 chunks into a single mp3.

### ISSUE THREAD

**Issue by jaymo107** [jackedgson/crunker#2]
Hi, quick question if that's ok? I've created a voice recording system which splits up a recording into multiple mp3 blobs, could this be used to take chunks of mp3's and then turn them into a single mp3? 

Reason I've asked is I've had trouble with other concatenation methods which seems to leave little clicks between each of the chunks when they're appended, and after research I know that mp3's have headers on them which needs to be stripped out etc or concatenation isn't smooth. Would this be a valid use case to use this? Just thought I'd ask before I dive in, although it's probably best just to try this for myself.

Thanks!

**Comment by jaggad** [comment]
@jaymo107 I'd say this will work as I've tested mp3 concatenation fine. However, the only way to know is to try it out. Let me know if you had success and feel free to create a PR if you encounter an issue.
