### ISSUE TITLE
Must be `forEach` in lieu of `map`

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jackedgson/crunker#20]
https://github.com/jackedgson/crunker/blob/ecaf6f8400c492d0d5c5c4401acc692b1897f8b9/src/crunker.js#L49

Because returned array is not used.

**Comment by jaggad** [comment]
Good spot, feel free to make a PR with the different changes you've discussed and I'll review and merge.

**Comment by Alynva** [comment]
Fixed by 836b2a973bfe8a0e5a9db2dc9839a2a7ebcf61a6
