### ISSUE TITLE
concat not seamless.

### ISSUE THREAD

**Issue by soundreactor** [jackedgson/crunker#22]
so i just tried the concat and the file it produced has a tiny seam/"hickup" where 2 audios are merged. in music very noticeable. is there a fix for that?
or what could i try?
quick test:
http://mrvv.net/scdl/fts/crunker.html

**Comment by Alynva** [comment]
The problem is with your sample 2, there is a little gap:

![image](https://user-images.githubusercontent.com/12958674/88823570-9ea57100-d19b-11ea-81d1-825b73ad45bf.png)
