### ISSUE TITLE
merging audio files in windows 10 produce audio files with pitched down, working fine in other OS

### ISSUE THREAD

**Issue by Shyam-Prasad-Gupta** [jackedgson/crunker#23]
Hi Jack, I am using crunker library to merge the WebM format audio files. It is working fine in all OS except Windows 10. The merged audio files pitch is down and the length of the audio file is also increased.
Do you have any idea about it why it is happening or its possible solution?

**Comment by jaggad** [comment]
It may be possible that the Web Audio API implementation is not supported in whichever browser you are using on that OS (Edge/IE). I haven't worked on this for a while so I'm not up to date with this, unfortunately that's about all the help I can add at this stage.

A place potentially worth looking is the 'headers' for the mp3, this may have something to do with it.

**Comment by Alynva** [comment]
@Shyam-Prasad-Gupta do you have a repository to reproduce?

**Comment by mydoghasworms** [comment]
I have the same, but with concatenating some audio samples. (Also on Windows 10)

**Comment by shyam-gupta-hng** [comment]
Hi @Alynva and @mydoghasworms , changing in audio sample bitrate/sample rate worked for me, it also depends on your hardware as well so please consider that at well.

**Comment by mydoghasworms** [comment]
@shyam-gupta-hng I have actually thought of converting all my samples to have the same bitrate. Is that what you are talking about?
I have now also had the same issue on Android, but when I tried it on Linux, it seemed to work OK. 🤷‍♂

**Comment by shyam-gupta-hng** [comment]
Hi, here is the link to website, having an instruction to change the audio sample rate n windows.
https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/how-to-change-sound-control-panel-settings-in/5a70718b-7ecf-4547-a64a-22efda8da0c2
