### ISSUE TITLE
Merging results in large waveform file.

### ISSUE THREAD

**Issue by ChadCleveland** [jackedgson/crunker#25]
Wonderful tool - so helpful.

I am merging two audio tracks - a background track that is uploaded and a voice track that is recorded in the browser.

The merged track is ending up quite a bit larger than the original tracks.

I found your recommendation to reduce the sample rate [ https://github.com/jackedgson/crunker/issues/24 ]. This did reduce the file size by half, but it's still very large and came at the expense of fidelity.

A specific example:
Background mp3 | 1hr | 76mb
Recording | 25sec | 400kb
Crunker result | 1 hr | 275mb (550mb before adjusting the Crunker constructor sample rate to 22050)

Is it possible to get the file size down in Crunker?

**Comment by jaggad** [comment]
@LightbulbServices Perhaps you could reduce the input file sizes. Or look and see if there is a WAV file compression algorithm you could add or implement.

The only way I know how would be to reduce sampler ate, and therefore the quality if size is an issue.

Hope this helps

**Comment by ChadCleveland** [comment]
Thank you for the quick reply. Helpful to know there isn't a setting in crunker to change, so I can do some research elsewhere. Love the tool, the merge function is amazing!
