### ISSUE TITLE
Concatenation

### ISSUE THREAD

**Issue by hussam123-lab** [jackedgson/crunker#33]
```js
  mediaRecorder.onstop = (ev)=>{
                let blob = new Blob(chunks, { 'type' : 'video/mp3;' });
                chunks = [];
                let videoURL = window.URL.createObjectURL(blob);
                vidSave.src = videoURL;
            }
        })
        .catch(function(err) { 
            console.log(err.name, err.message); 
        });

        document.querySelector('#press').addEventListener('click',function() {
            var audio =  new Crunker.default({ sampleRate: 44100 });
            let file = document.querySelector('#vid2');

            audio
            .fetchAudio("file","example1.mp3")
            .then(buffers => audio.concatAudio(buffers))
            .then(merged => audio.export(merged, "audio/wav"))
    .then(output => audio.download(output.blob))
    .catch(error => {
      throw new Error(error);
    });
        });
```

Is an implementation like this valid using your library? I am trying to get an audio recording from the user through the browser. I then convert it into a blob and try to concatenate that blob with a local audio file. Is this possible with the library?

**Comment by Alynva** [comment]
Yes, but the parameter in `fetchAudio` should be the audio source url.

**Comment by hussam123-lab** [comment]
So if I was to embed 2 audio files into the html document is there a way I could concatenate those two without using their file paths?

**Comment by Alynva** [comment]
Basically, you just have to access the source attribute from the DOM element, so, in our example, `file.src`

**Comment by Alynva** [comment]
Solved with [the newer examples](https://github.com/jackedgson/crunker/tree/dev/examples#examples)

If you have more questions, let us know.
