### ISSUE TITLE
Embedding Url

### ISSUE THREAD

**Issue by hussam123-lab** [jackedgson/crunker#34]
```html
<audio src="example.mp3" id = 'ex'></audio>
<audio src="example1.mp3" id = 'ex1'></audio>
```

```js
var f = document.getElementById('ex').src
var f1 = document.getElementById('ex1').src
```

Whenever I do:

```js
audio
    .fetchAudio("f", "f1")
```

it says it cant seem to find the file, even though Im calling the URl.

**Comment by Alynva** [comment]
You are not  using the variables `f` nor `f1`. You did put these names into quotes, so the function received just these names, not they values. You have to do this:

```js
audio.fetchAudio(f, f1)
```

**Comment by Alynva** [comment]
I think that was already resolved, if you have any more questions let us know
