### ISSUE TITLE
size - sampleRate slow motion effect

### ISSUE THREAD

**Issue by eeepad86** [jackedgson/crunker#36]
hi, i am using crunker to merge 2 mp3 audio files (voice and background).
voice.mp3 is 1mb
background.mp3 is 780kb
after merged the files the size of result.mp3 is about 11mb.

I followed the advice to change the sampleRate from 44100 to 22050, but i noticed that the background.mp3 slows down.
I have the impression that it went from 1x to 0.5x
**Is there a way to reduce the size** of result.mp3 **without creating the slow motion effect**?
Thanks

**Comment by jaggad** [comment]
Is it just the background track that is slowed? If so it would likely have something to do with the input audio file. Not sure of the use case, my first response would be to try converting mp3 to wave or running the files through a compressor to see if that changes the outcome.

Given we haven't seen this before it could be an oddly formatted file, the in-code fix would probably be related to 
these lines: https://github.com/jackedgson/crunker/blob/57489448bc0f5a2a847461aab91bcd81cc51ceb5/src/crunker.js#L33 

Open to pull requests if the initial fix doesn't work and you can determine a solution.

**Comment by jaggad** [comment]
Please also see https://github.com/jackedgson/crunker/issues/23 for related discussion.

**Comment by eeepad86** [comment]
> Is it just the background track that is slowed? If so it would likely have something to do with the input audio file. Not sure of the use case, my first response would be to try converting mp3 to wave or running the files through a compressor to see if that changes the outcome.
> 
> Given we haven't seen this before it could be an oddly formatted file, the in-code fix would probably be related to
> these lines:
> 
> https://github.com/jackedgson/crunker/blob/57489448bc0f5a2a847461aab91bcd81cc51ceb5/src/crunker.js#L33
> 
> Open to pull requests if the initial fix doesn't work and you can determine a solution.

Hi, no it's not just the background, but the final merged audio.
This only happens if I change sampleRate from 44100 to a lower value.
Instead if I don't change it, it works well

**Comment by Codezen** [comment]
The sample rate needs to change to whatever the browser rate is. I had one computer that has audio set to 48000 and another with 44100 in windows audio settings. To fix it I used this code:

var AudioContext = window.AudioContext || window.webkitAudioContext;
var audioCtx = new AudioContext();
var sampleRate = audioCtx.sampleRate;
var crunker = new Crunker.default({ sampleRate });

**Comment by davwheat** [comment]
Ooh, so this would explain the issue I was having too! Thanks for the explanation. I might try to patch this as a default value as a PR.

**Comment by jaggad** [comment]
That would be appreciated @davwheat
