### ISSUE TITLE
Turn Audio Node into blob or buffers

### ISSUE THREAD

**Issue by stjet** [jackedgson/crunker#48]
Hi! This isn't an issue with your library, sorry for putting it here.
I am trying to create either a blob url or a buffer array so I can merge it (with your library). However, the audio isn't a file, but a, OscillatorNode. I can't figure out how to get a blob url or buffer array from the node. Thanks for making this library, and hope you can help.
https://developer.mozilla.org/en-US/docs/Web/API/OscillatorNode

**Comment by jaggad** [comment]
@jetstream0 

That's quite a challenging one. I couldn't find much anywhere on converting a AudioNode such as OscillatorNode into a AudioBufferArray.

The answer could be here:
https://stackoverflow.com/questions/58029703/is-it-possible-to-convert-frequency-hertz-array-to-audiobuffer-using-javascript

Looks like the trick could be to use an OfflineAudioContext. Anyway that SO answer seems to achieve a similar desired result, if not a little more complex with timings.

```
offlineAudioContext
    .startRendering()
    .then((audioBuffer) => console.log(audioBuffer));
```

Good luck, if you come up with an elegant solution please come back and we can update the library to include an example for this use case or some simple function to automatically take in AudioNodes and convert to a buffer.

**Comment by stjet** [comment]
Thank you, I will check the answer out.

**Comment by stjet** [comment]
Nice, it works

**Comment by stjet** [comment]
Alright, fixed a couple of bugs, and now it works even better. Thank you @jackedgson for taking the time to help me, I honestly couldn't have finished my project without you.

**Comment by stjet** [comment]
And of the function to convert AudioNodes to buffers, I will work on it and PR it when I have the time, thanks again.

**Comment by jaggad** [comment]
You're welcome, glad you could solve it and get the project working!
