### ISSUE TITLE
fetchAudio parameters as an array

### ISSUE THREAD

**Issue by hphaavikko** [jackedgson/crunker#59]
It would be extermely useful to be able to pass an array of song urls to fetchAudio instead of separate parameters. So in addition to 

`crunker.fetchAudio(songURL, anotherSongURL)`

an option to pass song urls like this

`crunker.fetchAudio(arrayOfSongURLs)`

would make a lot of sense in my opinion, for example in situations where the song urls are generated dynamically and we don't know how many of them there will be etc.

Edit: Yes I know this can be done for example using spread operator but anyways it would be nice to have this option.

**Comment by davwheat** [comment]
In modern JS, you can use the spread operator for this:

```js
const songs = []

crunker.fetchAudio(...songs)
```

**Comment by davwheat** [comment]
Ah I see you've edited. You can also use `crunker.fetchAudio.apply(null, songsArray)`.

I don't see the need to implement a second method to allow for this, as it would only call the spread operator or apply internally anyway.

**Comment by hphaavikko** [comment]
Ok, no worries, thanks for the quick reply!
