### ISSUE TITLE
Does any video alternative exists?

### ISSUE THREAD

**Issue by italodeandra** [jackedgson/crunker#60]
Hey team,

I need to play a video (webm) and an audio (m4a) file at the same time on a browser that only accepts one media playing at a time (if I try to play them simultaneously on separate <video> and <audio> elements, the previous gets paused automatically).

So I was looking for something for merging those two and found this library but for only audio. Does any video alternative exists?

Is that something that is almost impossible? Because it's been really hard to find anything. But I know that YouTube player does that. It downloads two separate files (video/webm and audio/webm) and merges them into one blob.

**Comment by jaggad** [comment]
Sorry I am know aware of any library that does this. Sounds difficult and may not exist as a library. 

You are likely better off using a third party API or something like ffmpeg in node or python.

**Comment by italodeandra** [comment]
Hi @jackedgson, thanks for the reply.

It's currently not possible for me to convert the files on the backend, since they are served from a bucket and we don't control this bucket so we can't also keep them converted because it will cost more.

YouTube does exactly that and I'm desperately looking for something similar on the internet, without success. I have no idea on how they accomplish that. Not only on the web version, they even do this on the iOS/Android app and on TV apps/browsers. They use the same separate files for video and audio (for the same reason, they want to save money).

They load each file from their `playback` endpoint and load both together on a blob if I understand correctly, but I can't find how they created this blob.

**Comment by no-1ne** [comment]
Can this help https://github.com/t-mullen/video-stream-merger

**Comment by italodeandra** [comment]
Hey @no-1ne,

For now I gave up developing my own solution. I spent too much time on it.

But after checking the `video-stream-merger` it seems it might work really well with livestream, but in my case I need chunked playback (like YouTube). Thanks though.

For now I'll close this.
