### ISSUE TITLE
crunker-master/examples/server/index.html  not working?

### ISSUE THREAD

**Issue by lotuspoolcnhz** [jackedgson/crunker#62]
Hello !
I am using this repository to merge 2 audio files.
I  found some error in console of chrome   "crunker-master/examples/server/index.html".
Please give me somey suggestions?

crunker.js:1 Fetch API cannot load file:///E:/crunker-master/examples/server/1.mp3. URL scheme "file" is not supported.
(anonymous) @ crunker.js:1
value @ crunker.js:1
doTheWork @ index.html:27
handleMerge @ index.html:18
onclick @ index.html:10
19:22:36.849 crunker.js:1 Fetch API cannot load file:///E:/crunker-master/examples/server/2.mp3. URL scheme "file" is not supported.
(anonymous) @ crunker.js:1
value @ crunker.js:1
doTheWork @ index.html:27
handleMerge @ index.html:18
onclick @ index.html:10
19:22:36.850 crunker.js:1  Uncaught (in promise) TypeError: Failed to fetch
    at crunker.js:1
    at Array.map (<anonymous>)
    at e.value (crunker.js:1)
    at doTheWork (index.html:27)
    at handleMerge (index.html:18)
    at HTMLButtonElement.onclick (index.html:10)

**Comment by davwheat** [comment]
This is a browser limitation for security, preventing sites from maliciously enumerating files on your local computer, and is not an issue with Crunker.

You'll need to launch the examples folder with a web server, such as npm's [`http-server`](https://www.npmjs.com/package/http-server).

**Comment by davwheat** [comment]
Now you mention it, though, the examples won't work whatsoever since Crunker is now written in Typescript, but the example still attempt to load Crunker from a `.js` file.

**Comment by jaggad** [comment]
Wonder if we should add to the docs a command to run the examples with ts-node  to make this clearer and a command. That may not be the best though.

I imagine most people will prefer to just copy the example as a starting point so better to reference crunker from a delivery cdn like jsdelivr for example.

**Comment by jaggad** [comment]
I don't think this issue is ready to be closed. We simply need to update the reference to crunkerjs with the unpkg link we use in the server examples. 

Should be an easy 2 min fix

**Comment by davwheat** [comment]
The examples should also be able to be hosted on GitHub Pages to alleviate the issue, too (they actually are, but you have to directly enter the URL: https://jackedgson.github.io/crunker/examples/client/index.html)

**Comment by jaggad** [comment]
Hmm, I'll see if I can get a better GitHub url for that and add it to the repo description.

Are you able to do a quick or to replace the relative reference to src with the unpkg url in the meantime?

**Comment by davwheat** [comment]
Yeah, of course.

**Comment by lotuspoolcnhz** [comment]
Thanks a lot!

**Comment by jaggad** [comment]
Actually @davwheat I've updated it now and also made both use latest version, plus released the package to version 1.3.0 based on previous changed I forgot to publish. So no need to update anymore.

**Comment by jaggad** [comment]
Have also added URL now as suggested, thanks for that Dave. Good find @lotuspoolcnhz going to close this one now.
