### ISSUE TITLE
Create NPM Package

### ISSUE THREAD

**Issue by jaggad** [jackedgson/crunker#7]
What needs to be done to turn this library into an npm package?

**Comment by fzxt** [comment]
You'll probably want to tweak / add these files:
- gitignore
- npmignore
- PUBLISH_NPM.md (optional, some instructions on publishing to NPM)?
- package.json

Working on a PR for your review.

**Comment by jaggad** [comment]
Bam, working npm installation. https://www.npmjs.com/package/crunker

Should verify it is in fact working by testing with another project, but, all in good time.
