### ISSUE TITLE
enhancement Beatmachine

### ISSUE THREAD

**Issue by Thecoolpeople** [jackedgson/crunker#71]
Hello out there.

I have written a small Beatmachine, but in pure js. Perhaps one of you want to implement that in typescript and add it to crunker.

I have no experience in typescript, so I am not able to help.

## Code
```
mergeOneLine = async function(crunker, buffer, times){
    let audios = times.map(t => crunker.padAudio(buffer, 0, t))
    return crunker.mergeAudio(audios)
}

beatBuilder = async function(crunker, beatConf, buffers, beatTiming){
    let beatLines = await Promise.all(buffers.map((_,i) => {
        return mergeOneLine(crunker, buffers[i], beatTiming[i].map(bt => bt*beatConf.timing))
    }))
    let beat = await crunker.mergeAudio(beatLines)
    return await mergeOneLine(crunker, beat, Array.from(Array(beatConf.repeats).keys()).map(e => beatConf.delayStart+e*beatConf.beats*beatConf.timing))
}

window.onload = async function(){
    let crunker = new Crunker.default({sampleRate:96000});
    let [hihats] = await crunker.fetchAudio('./drumms_Hi-Hats_Open_Hat.mp3');
    let [dirtBase] = await crunker.fetchAudio('./drumms_dirt_base.mp3');
    
    //add pause to audio
    beat = await beatBuilder(crunker, {delayStart: 1, timing:0.5, repeats: 4, beats: 4},
        [dirtBase, hihats], [
        [0, 1.5, 2],
        [1, 3]
    ])
    
    
    let merged = await crunker.mergeAudio([beat])
    crunker.play(merged);
    let output = await crunker.export(merged, 'audio/ogg');
    await crunker.download(output.blob, 'merged');
}
```

## Description:
mergeOneLine will generate a repeated sound at the timestamps times
beatBuilder will generate a buffer from multiple sounds and timestamps of that sound and will repeat that x times

Have a nice day!

**Comment by jaggad** [comment]
The code here look pretty good. It basically is typescript since TS has inferred types so won't take much effort. 

Just change the let to const to more accurately reflect most/all of these vars are immutable.

I think this would best belong inside the examples directory rather than be added to Crunker itself in any way.

You could probably create a PR as is in pure js in the example dir

**Comment by jaggad** [comment]
Closed by https://github.com/jackedgson/crunker/pull/72
