### ISSUE TITLE
Misleading README and method naming regarding format of exported file

### ISSUE THREAD

**Issue by gurumov** [jackedgson/crunker#73]
This is a nice little library and I was happy to use it and learn from it.
Sadly it turns out that it ONLY exports in WAV format, regardless of what the chosen MIME type is.
As even the README examples show exporting with "audio/mp3" I believed that the library does it and only after implementing everything realized that the files are much larger and WAV indeed.

Digging in the code revealed a comment about this, but I think it should be explicitly stated somewhere in the README.
Personally, I would suggest the method to be renamed to "wav_export" in a potential future release 

Thanks for the consideration

**Comment by Alynva** [comment]
Just for reference, here is the PR about this: https://github.com/jackedgson/crunker/pull/57. The [commit message](https://github.com/jackedgson/crunker/commit/46ea8514d85919f660b30389482bf6276bdcc2cc) has more detailed info about this behavior.

**Comment by jaggad** [comment]
Closed by #78
