### ISSUE TITLE
crunker.play(buffer) error buffer is not defined

### ISSUE THREAD

**Issue by JanVeb** [jackedgson/crunker#76]
Hi there, im stuck at playing audio file, im able to download it, and its great, just can't figure out how to play it.

As well, is it possible to load contacted audio to waveSurfer? Or how can I locate where is concacted audio so I can play it afterwards?

**Comment by jaggad** [comment]
The audio file is stored as a blob. The browser allows blob urls to be downloaded to mp3. When you say you can't figure out how to play it, do you mean you can't play the downloaded wav file?

Or you can't fire out how to play it before downloading?

**Comment by JanVeb** [comment]
I can't play it before downloading

Not sure where should I call
crunker.play(buffer)
After
let crunker = new Crunker();

crunker
  .fetchAudio('/voice.mp3', '/background.mp3')
  .then((buffers) => crunker.mergeAudio(buffers))
  .then((merged) => crunker.export(merged, 'audio/mp3'))
  .then((output) => crunker.download(output.blob))
  .catch((error) => {
    throw new Error(error);
  });

It says buffer is not defined

**Comment by jaggad** [comment]
Can you try:

```
crunker
  .fetchAudio('/song.mp3', '/another-song.mp3')
  .then((buffers) => {
    return crunker.mergeAudio(buffers);
  })
  .then((merged) => {
    return crunker.play(merged);
  })
`

**Comment by Alynva** [comment]
@JanVeb the variable is not defined in the global scope. You have to use that `play` method where you have the `buffer` variable.

**Comment by JanVeb** [comment]
Thank you, it's working now
