### ISSUE TITLE
Merging files at different times, fade option?

### ISSUE THREAD

**Issue by JanVeb** [jackedgson/crunker#79]
Hi there, I would like to use crunker to merge Piano samples into Piano scores

Would need ability to merge sound samples at different times, is this possible?

Then as well don't want these sounds to play to the end, as most are long well beyond 5 seconds, but I need them to play only for fraction of second, 0.125, 0.25 seconds etc, is it possible to fade out sounds at desired time or could it be possible in any other way?

**Comment by MikeyZat** [comment]
Theoretically speaking, I think that would be possible but it is far beyond current `Crunker` capabilities.

**Comment by JanVeb** [comment]
Okay, thank, looking into others options, if I don't figure it out, will try and do it it Crunker

**Comment by jaggad** [comment]
Cool. I think this is aligned with the vision of Crunker. We also have padAudio method to offset audios.

For what it's worth. In my original commerical use case ( which this was extracted from ) I had functionality to start audios at particular time stamps and play them through. With fade at the beginning and end of the final audio.

Everything you've suggested is possible as far as I can recall. I don't have the time to write the code lately but all contributions aligned with the main purpose are welcome.
