### ISSUE TITLE
Progress Report

### ISSUE THREAD

**Issue by aintHuman** [jackedgson/crunker#80]
Does this library have any kind of event or callback function to report on the progress of a particular concatenation or merge ? 

I have a situation where I might need to concatenate many many (like 50+) files, and it would be good to be able to report to the user as the progress moves from 0 to 100% completion. 

By extension, the estimated time remaining for completion could also be reported.

**Comment by MikeyZat** [comment]
No, it doesn't. I think it should be quite straightforward to add it inside the `concat` or `merge` methods (emitting events or sth), the question is: should this be really included in the core library?

**Comment by jaggad** [comment]
Simplest solution I can think of, though test it for performance would be to concat 2 at a time in your code as a promise and then increment a counter after each concat returns passing in the concatonated file from previous run as the input for the next one.

For timing, just get average time by starting Date.now() before the concat and ending it when concat promise resolves. get avg time for concat, then update it for each one with new avg estimate.

E.g:

1. `a` + `b` ( 1 / 100 )
2. `ab` + `c` ( 2 / 100 )
3. `abc` + `d` ( 3 / 100 )
4. etc.

That should work fine, no need to overcomplicate it. How does the performance go for something like this?

**Comment by aintHuman** [comment]
That could work, and it would be more accurate if firstly the duration of each was read from the file header or something, so that a fraction of total for each step could be determined ...

But what I really had in mind, is some event emissions similar to what is used here:

https://github.com/fluent-ffmpeg/node-fluent-ffmpeg

**Comment by jaggad** [comment]
I don't have the capacity to take this on right now, would you be interested in contributing to the repo with this feature @aintHuman?

Here's an example untested implementation 

```ts
import { EventEmitter } from "node:events";

class CrunkerEventExample {
  concatProgress = 0.5;
  emitter = new EventEmitter();

  concat() {
    this.emitter.emit("concat", this.concatProgress);
  }

  $on(eventName: "concat" | "merge", cb: () => void) {
    return this.emitter.on(eventName, cb);
  }
}

new CrunkerEventExample().$on("concat", () => {
  //
});
```

**Comment by davwheat** [comment]
Remember we can't use node events, as Crunker is for use in the browser too.

**Comment by aintHuman** [comment]
> I don't have the capacity to take this on right now, would you be interested in contributing to the repo with this feature @aintHuman?
> 
> Here's an example untested implementation
> 
> ```ts
> import { EventEmitter } from "node:events";
> 
> class CrunkerEventExample {
>   concatProgress = 0.5;
>   emitter = new EventEmitter();
> 
>   concat() {
>     this.emitter.emit("concat", this.concatProgress);
>   }
> 
>   $on(eventName: "concat" | "merge", cb: () => void) {
>     return this.emitter.on(eventName, cb);
>   }
> }
> 
> new CrunkerEventExample().$on("concat", () => {
>   //
> });
> ```

I have actually moved over to using audioconcat, since I can concat mp3 files directly on the server side with about an order of magnitude or more (estimated) performance gain. Basically I needed to concat 50 or 100 files downloaded from s3 bucket, to produce a single file which is then uploaded back to S3 bucket, and made available for download directly from s3 bucket via the client. So given the issues I raised and the work involved to resolve them, and how straightforward it was to use audioconcat and the performance benefit, I decided to go that way instead ...

**Comment by jaggad** [comment]
Audio manipulation is always preferable on the server so lower level code can be used for performance gains as pointed out. As browser support is critical for this library ( that is what it was created for ) I am going to close this issue.

Crunker is designed in part for when a tailored server side API isn't necesarrily available and the web audio api is required.
