### ISSUE TITLE
Crunker is not a constructor

### ISSUE THREAD

**Issue by aowright** [jackedgson/crunker#86]
I'm very new to using external modules, so this is most definitely a fault on my part, but I'm trying to implement the example shown after installing crunker, and I'm getting the error "Crunker is not a constructor". This is a snapshot of the code:

try {
            let crunker = new Crunker();
            crunker
            .fetchAudio('/audio1.mp3', '/audio2.mp3')
            .then((buffers) => crunker.mergeAudio(buffers))
            .then((merged) => crunker.export(merged, 'final/mp3'))
            .then((output) => crunker.download(output.blob))
            .catch((error) => {
                throw new Error(error);
            });
        }
        catch(err) {
            document.getElementById("update").innerHTML = err.message;
        }

I'd appreciate any help on this :)

**Comment by davwheat** [comment]
How are you including Crunker in your source code?

**Comment by aowright** [comment]
> How are you including Crunker in your source code?

I using this line in the head of my HTML file:

<script src="https://unpkg.com/crunker@latest/dist/crunker.js"></script>

as I saw it used in the Crunker examples.
Is there some way I should be importing it in my JavaScript file?

**Comment by davwheat** [comment]
Ummm, that shouldn't happen! It seems like the examples themselves are broken in the same way, actually!

For now, try adding this under your `<script src="...">`:

```html
<script>
  window.Crunker = window.Crunker.default;
</script>
```

This should fix your issue for now.

The better solution, in my opinion, would be using browser ES module support. I'll try and get the examples updated to demonstrate this.

**Comment by aowright** [comment]
Brilliant, it works now, thank you so much for your help :)
