### ISSUE TITLE
Converting files to buffers manually

### ISSUE THREAD

**Issue by aowright** [jackedgson/crunker#88]
Sorry to be coming in with so many questions, but I'm trying to merge files from an array:

const tracks = ["audio1.mp3", "audio2.mp3"];

document.getElementById("option1").onclick = async function() {
    
    try{
        const crunker = new Crunker.default();
        const buffers = await Promise.all(
            Array.from(tracks).map(async (file) => crunker._context.decodeAudioData(await file.arrayBuffer()))
        );
        const merged = await crunker["mergeAudio"](buffers);
        const output = await crunker.export(merged, 'final/mp3');
        await crunker.download(output.blob, "merge");

        document.getElementById("update").innerHTML = "Button Pressed";
    }
    catch(err) {
        document.getElementById("update").innerHTML = err.message;
    }
};

but I'm getting the error:

file.arrayBuffer is not a function.

I tried to follow what happened in the client example, and I don't really know where I'm going wrong.

**Comment by davwheat** [comment]
I think your case is more suited to the server example. Take a look at that one.

**Comment by aowright** [comment]
> I think your case is more suited to the server example. Take a look at that one.

Thank you! I wasn't aware of the "..." to expand an array in JavaScript
