### ISSUE TITLE
Used in nextjs, server side error `ReferenceError: self is not defined`

### ISSUE THREAD

**Issue by hqw567** [jackedgson/crunker#97]
Using server error reporting in nextjs `ReferenceError: self is not defined`
  
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.17.1
Relevant Packages:
  next: 13.5.4

**Comment by hqw567** [comment]
Copy the original code crunker.ts for normal use.

**Comment by stevenbdf** [comment]
> Copy the original code crunker.ts for normal use.

This library relies on the Audio Web API which is not available in node.js (Nx Server side)

**Comment by kenny101** [comment]
I think you can also just disable server-side rendering with client side rendering enabled. This will allow your client to use the web API. I've done this on sveltekit and it should work the same way.

**Comment by 27medkamal** [comment]
I believe this is related to https://webpack.js.org/configuration/output/#outputglobalobject
